server:
  port: 8081

spring:
  application:
    name: reserva-api-gateway
  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: lb://APIRESERVA-USUARIO-SERVICE
          predicates:
            - Path=/api-usuario/**
        - id: reserva-service
          uri: lb://APIRESERVA-RESERVA-SERVICE
          predicates:
            - Path=/api-reserva/**

ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost